pipeline {
    agent any

    stages {

        stage('Setup') {
            steps {
                sh "pip install -r requirements"
                
            }
        }          


        stage('Test') {
            steps {
                sh "pytest"
                
            }
        }    
        
            
    }
}